[package]
name = "csv_sculptor_core"
version = "0.1.0-alpha.4"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
csv.workspace = true
thiserror.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
