[package]
name = "csv_sculptor_web"
version = "0.1.0-alpha.5"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
csv_sculptor_core = { version = "0.1.0-alpha.5", path = "../csv_sculptor_core" }
wasm-bindgen.workspace = true
js-sys.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
serde_json.workspace = true
